## Create

In [1]:
import numpy as np

In [2]:
#Not using np.array
a=([1,2,3])
b=([9,8,7])
c=a+b
print(c)

[1, 2, 3, 9, 8, 7]


In [3]:
type(c)

list

In [4]:
#Using np.array
a=np.array([[1,2,3]])
b=np.array([[9,8,7]])
c=a+b
print(c)

[[10 10 10]]


In [5]:
type(c)

numpy.ndarray

In [6]:
#In-built arrays
array1=np.random.rand(2,3,4) 
#2 is number of arrays,
# 3 is number of rows
#4 is number of columns
array1

array([[[0.98099402, 0.92706803, 0.66918558, 0.6596633 ],
        [0.20288303, 0.55906414, 0.22064885, 0.26861771],
        [0.28410647, 0.45601343, 0.78036534, 0.03711516]],

       [[0.77778546, 0.62458024, 0.73317347, 0.63520906],
        [0.51855194, 0.47112811, 0.63362492, 0.38730292],
        [0.53429474, 0.69902102, 0.21196182, 0.04850661]]])

In [7]:
np.random.randint(5,20,4)
#returning 4 random values between 5 to 20

array([12,  7, 11, 11])

In [8]:
#Here all values will be zeroes
a1=np.zeros([4,3])
a1
#4 is no. of rows
#3 is no. of columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#Here all values will be one
a2=np.ones([2,3])
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
a3=np.full([2,3],4)
# An array matrix with 2 rows and 3 col with value as 4 
a3

array([[4, 4, 4],
       [4, 4, 4]])

In [11]:
print('Shape : ',a3.shape)
print('Size : ',a3.size)

Shape :  (2, 3)
Size :  6


## Slicing

In [12]:
arrayA=array1[1]
arrayA
#indexing starts from 0 
#Since there are only two arrays in array1, array1[2] will give an error

array([[0.77778546, 0.62458024, 0.73317347, 0.63520906],
       [0.51855194, 0.47112811, 0.63362492, 0.38730292],
       [0.53429474, 0.69902102, 0.21196182, 0.04850661]])

In [13]:
slicer=array1[-1]
slicer
#It will slice arrays, not values in that array

array([[0.77778546, 0.62458024, 0.73317347, 0.63520906],
       [0.51855194, 0.47112811, 0.63362492, 0.38730292],
       [0.53429474, 0.69902102, 0.21196182, 0.04850661]])

In [14]:
#go on slicing
slicer1=array1[-1]
slicer2=array1[-1][0:3]
slicer3=array1[-1][0:3][2]
slicer4=array1[-1][0:3][2][0:2]
print('Selecting only 1 array :\n',slicer1)
print()
print('Selecting only 1 array with specific rows :\n',slicer2)
print()
print('Selecting only 1 array with specific rows and columns :\n',slicer3)
print()
print('Selecting only 1 array with specific rows and columns and values :\n',slicer4)

Selecting only 1 array :
 [[0.77778546 0.62458024 0.73317347 0.63520906]
 [0.51855194 0.47112811 0.63362492 0.38730292]
 [0.53429474 0.69902102 0.21196182 0.04850661]]

Selecting only 1 array with specific rows :
 [[0.77778546 0.62458024 0.73317347 0.63520906]
 [0.51855194 0.47112811 0.63362492 0.38730292]
 [0.53429474 0.69902102 0.21196182 0.04850661]]

Selecting only 1 array with specific rows and columns :
 [0.53429474 0.69902102 0.21196182 0.04850661]

Selecting only 1 array with specific rows and columns and values :
 [0.53429474 0.69902102]


## Maths and Stats Operations

In [15]:
# Basic maths 
#For addition,subtraction,multiplication and division ,it is not necessary to have a square matrix
A=np.random.rand(3,3)
B=np.random.rand(3,3)
#Here shapes of arrays should be same
C=np.add(A,B)  #For Addition
print(C)

[[0.37220601 1.48249647 1.10110548]
 [0.39897447 0.74093361 1.20973867]
 [1.41949167 0.80893297 0.94196359]]


In [16]:
D=np.subtract(A,B)   #For Subraction
print(D)

[[ 0.2064667  -0.4762519   0.84277407]
 [ 0.11235381  0.04405387 -0.34694624]
 [ 0.09674983 -0.39023722 -0.1613665 ]]


In [17]:
E=np.multiply(A,B)  #For Multiplication
print(E)

[[0.0239772  0.49274498 0.12554129]
 [0.03663931 0.13676047 0.33577399]
 [0.50139902 0.12552186 0.21531407]]


In [18]:
F=np.divide(A,B)  #For Division
print(F)

[[3.49146325 0.51371814 7.524751  ]
 [1.78398957 1.12643178 0.55424988]
 [1.14628679 0.34915456 0.7074919 ]]


In [19]:
#For Dot Product the matrix should be a square matrix
G=np.dot(A,B)  #For Dot Product
print(G)

[[0.73889253 1.04143702 0.96515897]
 [0.36274812 0.64581006 0.57650379]
 [0.35095903 1.04944623 0.4761816 ]]


In [20]:
#Statistics Function
H=np.sqrt(25)
I=np.abs(-2)
J=np.power(2,3)
K=np.log(25)
L=np.exp(3)
M=np.min(A)  #A is any list
N=np.max(B)  #B is any list

In [21]:
print('Square Root : ',H)
print('Absolute value : ',I)
print('Power : ',J)
print('Log : ',K)
print('Exponential : ',L)
print('Minimum of list : ',M)
print('Maximum of list : ',N)

Square Root :  5.0
Absolute value :  2
Power :  8
Log :  3.2188758248682006
Exponential :  20.085536923187668
Minimum of list :  0.20934787182288883
Maximum of list :  0.9793741875503489


## Update

In [22]:
# To update a value from a array.
a4=np.random.rand(2,4,3)
a4

array([[[0.25823798, 0.79444284, 0.69065952],
        [0.45596068, 0.09876345, 0.90251195],
        [0.67034868, 0.35079942, 0.82036213],
        [0.70001675, 0.63667088, 0.49533803]],

       [[0.80587534, 0.88395068, 0.30166643],
        [0.32346314, 0.27985575, 0.09792666],
        [0.45218085, 0.49709557, 0.16905831],
        [0.12559751, 0.76120281, 0.39805723]]])

In [23]:
# If we want to update the very first value
a4[1][0][0]=13
a4

array([[[ 0.25823798,  0.79444284,  0.69065952],
        [ 0.45596068,  0.09876345,  0.90251195],
        [ 0.67034868,  0.35079942,  0.82036213],
        [ 0.70001675,  0.63667088,  0.49533803]],

       [[13.        ,  0.88395068,  0.30166643],
        [ 0.32346314,  0.27985575,  0.09792666],
        [ 0.45218085,  0.49709557,  0.16905831],
        [ 0.12559751,  0.76120281,  0.39805723]]])

In [24]:
a4.sort()  #Sort rows wise only
a4

array([[[ 0.25823798,  0.69065952,  0.79444284],
        [ 0.09876345,  0.45596068,  0.90251195],
        [ 0.35079942,  0.67034868,  0.82036213],
        [ 0.49533803,  0.63667088,  0.70001675]],

       [[ 0.30166643,  0.88395068, 13.        ],
        [ 0.09792666,  0.27985575,  0.32346314],
        [ 0.16905831,  0.45218085,  0.49709557],
        [ 0.12559751,  0.39805723,  0.76120281]]])

In [25]:
a4.shape

(2, 4, 3)

In [26]:
a5=a4.reshape((1,2,-1)) #-1 specifies we are not interested in last value
a5.shape

(1, 2, 12)

In [27]:
#To add new values at the end ,use np.append
a6=np.zeros((5))
print('a6 is ',a6)
a7=np.append(a6,[3,4])
print('a7 is ',a7)

a6 is  [0. 0. 0. 0. 0.]
a7 is  [0. 0. 0. 0. 0. 3. 4.]


In [28]:
#To insert values in specific place (in between), use np.insert
a8=np.insert(a7,2,1)
a8
#Inserting value 1, in array a6 with 2nd position
#Indexing starts from 0

array([0., 0., 1., 0., 0., 0., 3., 4.])

# Delete

In [29]:
#Delete a segment of an array
a4

array([[[ 0.25823798,  0.69065952,  0.79444284],
        [ 0.09876345,  0.45596068,  0.90251195],
        [ 0.35079942,  0.67034868,  0.82036213],
        [ 0.49533803,  0.63667088,  0.70001675]],

       [[ 0.30166643,  0.88395068, 13.        ],
        [ 0.09792666,  0.27985575,  0.32346314],
        [ 0.16905831,  0.45218085,  0.49709557],
        [ 0.12559751,  0.39805723,  0.76120281]]])

In [30]:
np.delete(a4,0,axis=1)
#will delete 1st row of both the arrays
#axis =1 --> row

array([[[0.09876345, 0.45596068, 0.90251195],
        [0.35079942, 0.67034868, 0.82036213],
        [0.49533803, 0.63667088, 0.70001675]],

       [[0.09792666, 0.27985575, 0.32346314],
        [0.16905831, 0.45218085, 0.49709557],
        [0.12559751, 0.39805723, 0.76120281]]])